=== Holenkov/EPAM-Training-Projects/Task4XMLParsing/WebContent/WEB-INF/data/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/devices"
	xmlns:dev="http://www.example.com/devices" elementFormDefault="qualified">

	<element name="devices">
		<complexType>
			<sequence>
				<element ref="dev:device" minOccurs="16" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>


	<element name="device" type="dev:Device" abstract="true"></element>
	<element name="cpu" type="dev:CPU" substitutionGroup="dev:device"></element>
	<element name="display" type="dev:Display" substitutionGroup="dev:device"></element>
	<element name="motherboard" type="dev:Motherboard" substitutionGroup="dev:device"></element>
	<element name="mouse" type="dev:Mouse" substitutionGroup="dev:device"></element>
	<element name="ssd" type="dev:SSD" substitutionGroup="dev:device"></element>
	<element name="hdd" type="dev:HDD" substitutionGroup="dev:device"></element>

	<element name="type" type="dev:Type" abstract="true"></element>
	<element name="energy" type="dev:Energy" substitutionGroup="dev:type"></element>
	<element name="cooler" type="dev:Cooler" substitutionGroup="dev:type"></element>
	<element name="peripheral" type="dev:Peripheral" substitutionGroup="dev:type"></element>

	
	<complexType name="Device">
		<choice maxOccurs="unbounded">
			<element type="string" name="origin" default="No information" />
			<element name="price">
			 	<simpleType>
			 		<restriction base="double">
			 			<minExclusive value="0"/>
			 			<maxInclusive value="2000"/>
			 		</restriction>
			 	</simpleType>
			</element>
			<element type="boolean" name="isCritical" default="true" />
			<element name="types">
				<complexType>
					<sequence>
						<element ref="dev:type" 
						minOccurs="1" 
						maxOccurs="unbounded" />
					</sequence>
				</complexType>
			</element>
		</choice>
		<attribute type="string" name="name" id = "name" use="required" />
		<attribute type="gYearMonth" name="date" use="optional"
			default="2000-11" />
	</complexType>
	
	<complexType name="Type">
	</complexType>
	
	<complexType name="Energy">
		<complexContent>
			<extension base="dev:Type">
				<sequence>
					<element type="double" name="watt" minOccurs="1"
						maxOccurs="1" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="Cooler">
		<complexContent>
			<extension base="dev:Type">
				<sequence>
					<element type="boolean" name="isCooler" minOccurs="1"
						maxOccurs="1" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="Peripheral">
		<complexContent>
			<extension base="dev:Type">
				<sequence>
					<element type="boolean" name="isPeripheral" minOccurs="1"
						maxOccurs="1" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	


	<complexType name="CPU">
		<complexContent>
			<extension base="dev:Device">
				<sequence>
					<element type="int" name="frequency" minOccurs="1"
						maxOccurs="1" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>


	<complexType name="Motherboard">
		<complexContent>
			<extension base="dev:Device">
				<sequence>
					<element name="ports">
						<complexType>
							<sequence>
								<element name="port" type="dev:Port" minOccurs="0"
									maxOccurs="10" />
							</sequence>
						</complexType>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="Port">
		<restriction base="string">
			<enumeration value="COM"></enumeration>
			<enumeration value="USB"></enumeration>
			<enumeration value="LPT"></enumeration>
			<enumeration value="HDMI"></enumeration>
			<enumeration value="SATA"></enumeration>
			<enumeration value="PCI"></enumeration>
		</restriction>
	</simpleType>

	<complexType name="Display">
		<complexContent>
			<extension base="dev:Device">
				<sequence>
					<element type="int" name="resolutionX" />
					<element type="int" name="resolutionY" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Mouse">
		<complexContent>
			<extension base="dev:Device">
				<sequence>
					<element type="boolean" name="isWireless" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Store">
		<complexContent>
			<extension base="dev:Device">
				<sequence>
					<element type="int" name="capacity" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="HDD">
		<complexContent>
			<extension base="dev:Store">
				<sequence>
					<element type="int" name="rpm" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="SSD">
		<complexContent>
			<extension base="dev:Store">
				<sequence>
					<element type="int" name="speed" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

</schema>

=== Holenkov/EPAM-Training-Projects/Task4XMLParsing/WebContent/WEB-INF/data/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <devices xmlns:dev="http://www.example.com/devices"> -->

<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns="http://www.example.com/devices"
	xsi:schemaLocation="http://www.example.com/devices devices.xsd">

	<display name = "1 Samsung S710" date = "2019-01">
		<origin>Taiwan</origin>
		<price>151.50</price>
		<types>
			<energy>
				<watt>40.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>true</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<resolutionX>1024</resolutionX>
		<resolutionY>768</resolutionY>
	</display>
	
	<motherboard name = "2 MSI B450 Tomahawk" date = "2018-05">
		<origin>Malaysia</origin>
		<price>200.11</price>
		<types>
			<cooler>
				<isCooler>true</isCooler>
			</cooler>
			<energy>
				<watt>50.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<ports>
			<port>USB</port>
			<port>HDMI</port>
			<port>SATA</port>
			<port>COM</port>
		</ports>
	</motherboard>
	
	<display name = "3 Samsung S710" date = "2019-01">
		<origin>Taiwan</origin>
		<price>151.50</price>
		<types>
			<energy>
				<watt>40.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>true</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<resolutionX>1024</resolutionX>
		<resolutionY>768</resolutionY>
	</display>
	
	<mouse name = "4 Logitech m1" date = "2019-10">
		<origin>China</origin>
		<price>23.95</price>
		<types>
			<energy>
				<watt>0.01</watt>
			</energy>
			<peripheral>
				<isPeripheral>true</isPeripheral>
			</peripheral>
		</types>
		<isCritical>false</isCritical>
		<isWireless>true</isWireless>
	</mouse>
	
	
		<hdd name = "5 WD Caviar Blue" date = "2012-07">
		<origin>Japan</origin>
		<price>54.40</price>
		<types>
			<energy>
				<watt>5.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<capacity>100</capacity>
		<rpm>7200</rpm>
	</hdd>
	
	<mouse name = "6 Logitech m1" date = "2019-10">
		<origin>China</origin>
		<price>23.95</price>
		<types>
			<energy>
				<watt>0.01</watt>
			</energy>
			<peripheral>
				<isPeripheral>true</isPeripheral>
			</peripheral>
		</types>
		<isCritical>false</isCritical>
		<isWireless>true</isWireless>
	</mouse>
	
	<display  date = "2017-12" name = "7 Viewsonic R300">
		<origin>USA</origin>
		<price>105.50</price>
		<types>
			<energy>
				<watt>50.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>true</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<resolutionX>1024</resolutionX>
		<resolutionY>768</resolutionY>
	</display>
	
	<motherboard name = "8 MSI B450 Tomahawk" date = "2018-05">
		<origin>Malaysia</origin>
		<price>200.11</price>
		<types>
			<cooler>
				<isCooler>true</isCooler>
			</cooler>
			<energy>
				<watt>50.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<ports>
			<port>USB</port>
			<port>HDMI</port>
			<port>SATA</port>
			<port>COM</port>
		</ports>
	</motherboard>
	
	<cpu date = "2018-11" name = "9 AMD Ryzen 5 2600" >
		<origin>China</origin>
		<price>168.40</price>
		<types>
			<energy>
				<watt>5.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<frequency>2933</frequency>
	</cpu>
	
	<motherboard name = "10 MSI B450 Tomahawk" date = "2018-05">
		<origin>Malaysia</origin>
		<price>200.11</price>
		<types>
			<cooler>
				<isCooler>true</isCooler>
			</cooler>
			<energy>
				<watt>50.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<ports>
			<port>USB</port>
			<port>HDMI</port>
			<port>SATA</port>
			<port>COM</port>
		</ports>
	</motherboard>
	
	<ssd name = "11 Kingston A400" date = "2018-05">
		<origin>Malaysia</origin>
		<price>30.20</price>
		<types>
			<energy>
				<watt>5.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<capacity>120</capacity>
		<speed>500</speed>
	</ssd>
	
	<hdd name = "12 WD Caviar Blue" date = "2012-07">
		<origin>Japan</origin>
		<price>54.40</price>
		<types>
			<energy>
				<watt>5.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<capacity>100</capacity>
		<rpm>7200</rpm>
	</hdd>
	
	<cpu date = "2018-11" name = "13 AMD Ryzen 5 2600" >
		<origin>China</origin>
		<price>168.40</price>
		<types>
			<energy>
				<watt>5.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<frequency>2933</frequency>
	</cpu>
	
	<hdd name = "14 WD Caviar Blue" date = "2012-07">
		<origin>Japan</origin>
		<price>54.40</price>
		<types>
			<energy>
				<watt>5.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<capacity>100</capacity>
		<rpm>7200</rpm>
	</hdd>
	
	<ssd name = "15 Kingston A400" date = "2018-05">
		<origin>Malaysia</origin>
		<price>30.20</price>
		<types>
			<energy>
				<watt>5.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<capacity>120</capacity>
		<speed>500</speed>
	</ssd>
	
	<display  date = "2017-12" name = "16 Viewsonic R300">
		<origin>USA</origin>
		<price>105.50</price>
		<types>
			<energy>
				<watt>50.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>true</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<resolutionX>1024</resolutionX>
		<resolutionY>768</resolutionY>
	</display>
</devices>

=== Holenkov/EPAM-Training-Projects/Task4XMLParsing/data/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:dev="http://www.example.com/devices">

<!-- <devices xmlns:xsi="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://www.example.com/devices"
	xsi:schemaLocation="http://www.example.com/devices devices.xsd"> -->


	<mouse name = "Logitech m1" date = "05-2019">
		<origin>China</origin>
		<price>23.95</price>
		<types>
			<energy>
				<watt>0.01</watt>
			</energy>
			<peripheral>
				<isPeripheral>true</isPeripheral>
			</peripheral>
		</types>
		<isCritical>false</isCritical>
		<isWireless>true</isWireless>
	</mouse>
	
	<display name = "Samsung S710" date = "2019-01">
		<origin>Taiwan</origin>
		<price>151.50</price>
		<types>
			<energy>
				<watt>40.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>true</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<resolutionX>1024</resolutionX>
		<resolutionY>768</resolutionY>
	</display>
	
	<display  date = "2017-12" name = "Viewsonic R300">
		<origin>USA</origin>
		<price>105.50</price>
		<types>
			<energy>
				<watt>50.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>true</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<resolutionX>1024</resolutionX>
		<resolutionY>768</resolutionY>
	</display>
	
	<motherboard name = "MSI B450 Tomahawk" date = "2018-05">
		<origin>Malaysia</origin>
		<price>200.11</price>
		<types>
			<cooler>
				<isCooler>true</isCooler>
			</cooler>
			<energy>
				<watt>50.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<ports>
			<port>USB</port>
			<port>HDMI</port>
			<port>SATA</port>
			<port>COM</port>
		</ports>
	</motherboard>
	
	<ssd name = "Kingston A400" date = "2018-05">
		<origin>Malaysia</origin>
		<price>30.20</price>
		<types>
			<energy>
				<watt>5.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<capacity>120</capacity>
		<speed>500</speed>
	</ssd>
	
	<hdd name = "WD Caviar Blue" date = "2012-07">
		<origin>Japan</origin>
		<price>54.40</price>
		<types>
			<energy>
				<watt>5.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<capacity>100</capacity>
		<rpm>7200</rpm>
	</hdd>
	
	<cpu date = "2018-11" name = "AMD Ryzen 5 2600" >
		<origin>China</origin>
		<price>168.40</price>
		<types>
			<energy>
				<watt>5.0</watt>
			</energy>
			<peripheral>
				<isPeripheral>false</isPeripheral>
			</peripheral>
		</types>
		<isCritical>true</isCritical>
		<frequency>2933</frequency>
	</cpu>
</devices>
